#db:
#  url: jdbc:mysql://localhost:3306/petmanager_db
#  username: root
#  password: tjee1234
db:
  url: jdbc:mysql://sql12.freesqldatabase.com:3306/sql12823141
  username: sql12823141
  password: QxQCBJH3hz

upload:
  profile-path: tmp/uploads/profile
  board-path: tmp/uploads/board

mail:
  username: minyung0723@gmail.com  # Brevo에 발신자로 등록한 이메일
  password: hpzh jrox ormg clfs     # (기존 Gmail 앱비밀번호는 백업용으로 유지)

jwt:
  config:
    secret: springboard-jwt-secret-key-2026-change-this-please!!

BREVO_API_KEY: ${BREVO_API_KEY}